### ISSUE TITLE
Question about secondary msat data - population numbering

### ISSUE THREAD

**Issue by mariaemilyd** [mastoffel/bottleneck#1]
Hi Martin,

This is a question about the data for the paper, not an issue with the code per se. 

I'm working on a metaanalysis of Holocene demography of Arctic mammal species.  I'm wondering if you have a key or metadata to explain the population numbering in the ringed seal and bearded seal datasets , e.g. in file 'seal_genotypes_basic_30.xlsx' where populations are numbered 1-8. Going back to look at the source paper (Davis et al 2008) I can see population names but no way to match up names in the publication with the numbers in your dataset. Are you able to help? Thanks and best wishes,

Maria

**Comment by mastoffel** [comment]
Hi Maria,

unfortunately this is all the data we had (and needed) for our analysis, where the exact population names weren't that important. I suggest contacting the source paper authors for a more detailed data set!

Sorry I can't be more helpful here,

Martin

**Comment by mariaemilyd** [comment]
Hi Martin,

No problem, I will do that! Thanks for the quick reply!

Maria
